---
title: "Ch3 - Data Transformation - sumarise()"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## SUMMARISE()

```{r}
library(dplyr)
library(nycflights13)
data(flights)

# Example of summarise() function alone
# You can also use summarize() - these two are equivalent
summarise(flights, delay = mean(dep_delay, na.rm = TRUE))

# Combining summarise() with group_by() and a dplyr verb
by_day <- group_by(flights, year, month, day)
summarise(by_day, delay = mean(dep_delay, na.rm = TRUE))

# Multiple operations without a pipe
by_dest <- group_by(flights, dest)
delay <- summarise(by_dest,
count = n(),
dist = mean(distance, na.rm = TRUE),
delay = mean(arr_delay, na.rm = TRUE))
filter(delay, count > 20)

# There are three steps to prepare the flight delay data:
# 1) Group flights by destination
# 2) Summarise average distance, delay and number of flights
# 3) Filter to remove noisy points
# They can be chained together using pipeline '%>%'
mySummary <- flights %>%
group_by(dest) %>%
summarise(
count = n(),
dist = mean(distance, na.rm = TRUE),
delay = mean(arr_delay, na.rm = TRUE)) %>%
filter(count > 20)


# Using summarise() to measure standard deviation
# Distance to some destination has larger spread than others
flights %>%
group_by(dest) %>%
summarise(dist_sd = sd(distance, na.rm = TRUE)) %>%
arrange(desc(dist_sd))
```


## EXERCISES



1. Which carrier has the worst delays?


```{r}
flights %>%
  group_by(carrier) %>%
  summarise(arr_delay = mean(arr_delay, na.rm = TRUE)) %>%
  arrange(desc(arr_delay))
```



############################################################################
#############################################################################
2. For each destination, compute the total minutes of delay. For each flight,
compute the proportion of the total delay for its destination.

```{r}
flights %>%
  filter(!is.na(arr_delay), arr_delay > 0) %>%  
  group_by(dest) %>%
  mutate(arr_delay_total = sum(arr_delay),
         arr_delay_prop = arr_delay / arr_delay_total)
```


